### ISSUE TITLE
Imports not resolvable from http://purl.obolibrary.org/obo/cvdo.owl

### ISSUE THREAD

**Issue by psiotwo** [OpenLHS/CVDO#4]
Resolving http://purl.obolibrary.org/obo/cvdo.owl required resolution of a few more ontologies, three of which however are not resolvable (as shown in https://psiotwo.github.io/ontology-version-extractor/output.html):
- FMA, 
- OGMS, and 
- DOID imports

**Comment by serjoshua** [comment]
Following up on this since loading in OLS of CVDO from http://purl.obolibrary.org/obo/cvdo.owl is having issues. In summary, there is a failure importing http://purl.obolibrary.org/obo/cvdo/external/doid_import.owl.

Refer to https://github.com/EBISPOT/ols4/issues/453 for details regarding the error message in our pipeline.

**Comment by ethierjf** [comment]
Thanks for pointing this out. Our colleague in charge of this is currently not available but should be back early September.

JF Ethier - GRIIS.ca - Université de Sherbrooke
________________________________

**Comment by matentzn** [comment]
Following up on this - as is, the ontology is not usable by anyone using standard OWL tools. Do you have an ETA on when this will be fixed?

**Comment by ethierjf** [comment]
Thanks for the follow up. Should be fixed now

**Comment by pfabry** [comment]
An updated version with versioned imports is now available. cf. PR https://github.com/OpenLHS/CVDO/pull/5

**Comment by anitacaron** [comment]
I just tested the new version and imports are still not revolving.

```bash
Could not load imported ontology: <http://purl.obolibrary.org/obo/CVDO/releases/2013-04-04/imports/doid_import.owl> Cause: http://www.berkeleybop.org/ontologies/CVDO/releases/2013-04-04/imports/doid_import.owl
```

**Comment by matentzn** [comment]
@pfabry for this to work, 

1. CVDO in the IRI should be lower case (cvdo)
2. You need to create a corresponding release (2013-04-04) - this is ancient

But despite all this:

Its not good practice anymore to have imports in the release versions of ontologies. If you just use ROBOT and merge them it at release time, then the problem will go away without the need of changing anything about the IRIs!

**Comment by pfabry** [comment]
There is a merged version available in the repo, but it is not the release target. 
Our goal is to migrate this repo to an ODK pipeline, that should be done soon-ish. In the meantime I will make a new release with the merged version.

**Comment by ethierjf** [comment]
Honestly this is not a priority at this point for the team and others have been using the cvdo namespace for a different ontology.

Thanks for your feedback. It is on our roadmap and will be addressed accordingly 🙂

JF Ethier - GRIIS.ca - Université de Sherbrooke
________________________________

**Comment by anitacaron** [comment]
Great news! The ontology is now loading correctly! However, the version IRI is not resolving. It might need to update the purl configuration.
